name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y jq gnupg apt-utils curl gzip
      
      - name: Import GPG private key
        run: |
          gpg --batch --import <<EOF
          $GPG_PRIVATE_KEY
          EOF
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE }}
      
      - name: Download virgo-api .deb
        run: |
          curl -s https://api.github.com/repos/univrs-cloud/virgo-api/releases/latest \
          | jq -r '.assets[] | select(.name | endswith("_arm64.deb")) | .browser_download_url' \
          | xargs -I{} sh -c 'curl -L -o dists/stable/main/binary-arm64/$(basename "{}") "{}"'
      
      - name: Download virgo-ui .deb
        run: |
          curl -s https://api.github.com/repos/univrs-cloud/virgo-ui/releases/latest \
          | jq -r '.assets[] | select(.name | endswith("_arm64.deb")) | .browser_download_url' \
          | xargs -I{} sh -c 'curl -L -o dists/stable/main/binary-arm64/$(basename "{}") "{}"'
      
      - name: Sign and publish
        run: |
          git config --global user.name "Robert"
          git config --global user.email "veloaddict@@users.noreply.github.com"
          chmod +x publish.sh
          ./publish.sh
